---

- name: Install required software
  command: grep -r "php=7.0" /etc/ansible/facts.d/packages.fact
  register: php7
  ignore_errors: yes
- fail:
    msg: >
     Zendguard loader is not supported on PHP-7.0.
  when: php7.stdout


- name: Install required software
  shell: grep -r "php=" /etc/ansible/facts.d/packages.fact | tail -c 4
  register: php56
  ignore_errors: yes
#  when: php56.stdout
- debug: msg="PHP Version = {{php56.stdout}}"

- name: Creating directory ...
  file: path=/usr/local/zend recurse=yes state=directory

- name: Copying ZendGuard files
#  file: path=/usr/local/zend recurse=yes state=directory
  copy: src={{ php56.stdout }}_{{ item }} dest=/usr/local/zend/{{ php56.stdout }}_{{ item }} owner=root group=root
  with_items: ['opcache.so', 'ZendGuardLoader.so']

- name: Disabling Opcache ...
  lineinfile: dest=/etc/php5/mods-available/opcache.ini regexp='^(.*)zend_extension=' line=;zend_extension=opcache.so

- name: Disabling IonCube ...
  replace: dest=/etc/php5/mods-available/ioncube.ini regexp='^(.*)zend_extension' replace=';zend_extension'

- name: Configuring ZendGuardLoader ...
  template: src=zendguard.ini dest=/etc/php5/mods-available/

- name: Checking if FPM is intalled ...
  command: grep fpm /etc/ansible/facts.d/packages.fact
  register: reg1
- set_fact: fpm1 =='apache2'
  when: reg1.rc == 1
- set_fact: fpm1 =='fpm'
  when: reg2.rc == 0

- name: Creating Symlinks ...
  file: src=/etc/php5/mods-available/zendguard.ini dest=/etc/php5/{{ item }}/conf.d/06-zendguard.ini state=link
  with_items: ['{{ fpm1 }}', 'cli']
  notify:
      - restart apache2
      - restart php5-fpm
