---

- name: Install required software
  fail:
    msg: >
     Zendguard loader is not supported on PHP-{{ ansible_local.packages.version.php }}.
  when: ansible_local.packages.version.php == 7.0
  tags: phpv

- name: Creating directory ...
  file: path=/usr/local/zend recurse=yes state=directory

- name: Copying ZendGuard files
#  file: path=/usr/local/zend recurse=yes state=directory
  copy: src={{ ansible_local.packages.version.php }}_{{ item }} dest=/usr/local/zend/{{ ansible_local.packages.version.php }}_{{ item }} owner=root group=root
  with_items: ['opcache.so', 'ZendGuardLoader.so']

- name: Disabling Opcache ...
  lineinfile: dest=/etc/php5/mods-available/opcache.ini regexp='^(.*)zend_extension=' line=;zend_extension=opcache.so

- name: Disabling IonCube ...
  replace: dest=/etc/php5/mods-available/ioncube.ini regexp='^(.*)zend_extension' replace=';zend_extension'

- name: Configuring ZendGuardLoader ...
  template: src=zendguard.ini dest=/etc/php5/mods-available/

- set_fact: fpm1='{{ item.name }}'
  with_items: ['apache2', 'fpm']
  when: ansible_local.packages.version.fpm {{ item.action }} "enable"
  with_items:
    - { name: 'apache2', action: '==' }
    - { name: 'fpm', action: '!=' }
  tags: test1

- name: Creating Symlinks ...
  file: src=/etc/php5/mods-available/zendguard.ini dest=/etc/php5/{{ item }}/conf.d/06-zendguard.ini state=link
  with_items: ['{{ fpm1 }}', 'cli']
  notify:
      - restart apache2
      - restart php5-fpm
